# Generated by Django 5.1.7 on 2025-03-17 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cor', models.CharField(max_length=50)),
                ('estilo', models.BooleanField()),
                ('flg_p', models.BooleanField()),
                ('flg_m', models.BooleanField()),
                ('flg_g', models.BooleanField()),
                ('flg_gg', models.BooleanField()),
                ('flg_exg', models.BooleanField()),
                ('flg_sobmedida', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Congregacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('apelido', models.CharField(max_length=255)),
                ('congregacao', models.CharField(max_length=255)),
                ('telefone_whatsapp', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Remessa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pedido', models.DateField()),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('enviado', 'Enviado'), ('recebido', 'Recebido')], max_length=50)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='familia.evento')),
            ],
        ),
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('tipo_no_evento', models.CharField(choices=[('participante', 'Participante'), ('concentrador', 'Concentrador'), ('administrador', 'Administrador'), ('administrador_evento', 'Administrador de Evento')], max_length=50)),
                ('data_entrega_camisa', models.DateField(blank=True, null=True)),
                ('tamanho', models.CharField(choices=[('P', 'P'), ('M', 'M'), ('G', 'G'), ('GG', 'GG'), ('EXG', 'EXG'), ('SOB MEDIDA', 'Sob Medida')], max_length=10)),
                ('pagamento', models.BooleanField(default=False)),
                ('camisa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='familia.camisa')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='familia.evento')),
                ('remessa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='familia.remessa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='familia.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='CongregacaoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('congregacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='familia.congregacao')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='familia.evento')),
                ('concentrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='familia.usuario')),
            ],
            options={
                'unique_together': {('congregacao', 'evento')},
            },
        ),
    ]
