# Generated by Django 5.1.7 on 2025-03-31 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('familia', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscricao',
            name='data_entrega_camisa',
        ),
    ]
