# Generated by Django 5.1.7 on 2025-03-30 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familia', '0002_evento_created_at_evento_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscricao',
            name='remessa',
        ),
        migrations.RemoveField(
            model_name='inscricao',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='camisa',
            name='estilo',
            field=models.CharField(choices=[('normal', 'Normal'), ('babylook', 'Babylook')], max_length=10),
        ),
        migrations.AlterField(
            model_name='camisa',
            name='flg_exg',
            field=models.BooleanField(verbose_name='EXG'),
        ),
        migrations.AlterField(
            model_name='camisa',
            name='flg_g',
            field=models.BooleanField(verbose_name='G'),
        ),
        migrations.AlterField(
            model_name='camisa',
            name='flg_gg',
            field=models.BooleanField(verbose_name='GG'),
        ),
        migrations.AlterField(
            model_name='camisa',
            name='flg_m',
            field=models.BooleanField(verbose_name='M'),
        ),
        migrations.AlterField(
            model_name='camisa',
            name='flg_p',
            field=models.BooleanField(verbose_name='P'),
        ),
        migrations.AlterField(
            model_name='camisa',
            name='flg_sobmedida',
            field=models.BooleanField(verbose_name='Sob-Medida'),
        ),
    ]
