# Generated by Django 5.1.7 on 2025-03-31 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familia', '0003_remove_inscricao_remessa_remove_inscricao_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='nome_participante',
            field=models.CharField(default='Participante', max_length=255),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='telefone_whatsapp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
