# Generated by Django 5.1.7 on 2025-03-31 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familia', '0004_inscricao_cpf_inscricao_nome_participante_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscricao',
            name='nome_participante',
        ),
        migrations.RemoveField(
            model_name='inscricao',
            name='pagamento',
        ),
        migrations.RemoveField(
            model_name='inscricao',
            name='telefone_whatsapp',
        ),
        migrations.AddField(
            model_name='inscricao',
            name='apelido',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='congregacao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='familia.congregacao'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='nome_completo',
            field=models.CharField(default='Participante', max_length=255),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='pagamento_feito',
            field=models.BooleanField(default=False, verbose_name='Pagamento feito?'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='camisa_entregue',
            field=models.BooleanField(default=False, verbose_name='Camisa foi entregue?'),
        ),
    ]
